// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQYqJwyhsbRrfT2_0jghJNyenFVvnWqPI',
    appId: '1:99000635271:web:497a34818bd0cc0d454d22',
    messagingSenderId: '99000635271',
    projectId: 'spotifyx07',
    authDomain: 'spotifyx07.firebaseapp.com',
    storageBucket: 'spotifyx07.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkhKRE9Jr58DB4iCOOqwcyocEkhpT4veE',
    appId: '1:99000635271:android:f0a6b779772ca4f2454d22',
    messagingSenderId: '99000635271',
    projectId: 'spotifyx07',
    storageBucket: 'spotifyx07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB5yRrjToyvIc3dsI6DEGJZNUdHj5xFCw',
    appId: '1:99000635271:ios:8066c30da22a6d0a454d22',
    messagingSenderId: '99000635271',
    projectId: 'spotifyx07',
    storageBucket: 'spotifyx07.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB5yRrjToyvIc3dsI6DEGJZNUdHj5xFCw',
    appId: '1:99000635271:ios:8066c30da22a6d0a454d22',
    messagingSenderId: '99000635271',
    projectId: 'spotifyx07',
    storageBucket: 'spotifyx07.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQYqJwyhsbRrfT2_0jghJNyenFVvnWqPI',
    appId: '1:99000635271:web:78c48137939b58a4454d22',
    messagingSenderId: '99000635271',
    projectId: 'spotifyx07',
    authDomain: 'spotifyx07.firebaseapp.com',
    storageBucket: 'spotifyx07.firebasestorage.app',
  );
}
